version: "2.1"
services:
  redis-master:
    image: redis:6.2.0
    hostname: redis-master
    expose: 
      - "9001"
    ports:
      - "9200:9200"
    volumes:
      - ~/Projects/sh-valley/docker-conf/redis-cluster/redis_master.conf:/usr/local/etc/redis/redis.conf
      - ~/Projects/sh-valley/docker-conf/reids-cluster/data-master:/data
    networks:
      es-cluster-network:
        ipv4_address: 172.25.0.11
  redis-slave:
    image: redis:6.2.0
    hostname: redis-slave
    ports:
      - "5601:5601"
    volumes:
      - ~/Projects/sh-valley/docker-conf/redis-cluster/redis_slave.conf:/usr/local/etc/redis/redis.conf
      - ~/Projects/sh-valley/docker-conf/reids-cluster/data-slave:/data
    networks:
      es-cluster-network:
        ipv4_address: 172.25.0.12
networks:
  redis-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.25.0.0/16
        gateway: 172.25.0.1

