version: "2.1"
services:
  redis-master:
    image: redis:6.2.0
    hostname: redis-master
    command: redis-server /usr/local/etc/redis/redis.conf
    # expose: 
    #   - "6319"
    # ports:
    #   - "6319:6319"
    volumes:
      - ~/Projects/sh-valley/docker-conf/redis-cluster/master-slave/redis_master.conf:/usr/local/etc/redis/redis.conf
      - ~/Projects/sh-valley/docker-conf/reids-cluster/master-slave/data-master:/data
    networks:
      redis-network:
        ipv4_address: 172.25.0.11
  redis-slave:
    image: redis:6.2.0
    hostname: redis-slave
    command: redis-server /usr/local/etc/redis/redis.conf
    # ports:
    #   - "6319:6319"
    volumes:
      - ~/Projects/sh-valley/docker-conf/redis-cluster/master-slave/redis_slave.conf:/usr/local/etc/redis/redis.conf
      - ~/Projects/sh-valley/docker-conf/reids-cluster/master-slave/data-slave:/data
    networks:
      redis-network:
        ipv4_address: 172.25.0.12
networks:
  redis-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.25.0.0/16
        gateway: 172.25.0.1

