FROME centos

MAINTAINER cocowool@qq.com

ADD jdk-8u144-linux-x64.tar.gz /usr/local

WORKDIR /usr/local

ENV JAVA_HOME /sr/local/jdk1.8.0_144
ENV ACTIVEMQ_HOME /usr/local/apache-activemq-5.15.10

EXPOSE 61616 8161

ENTRYPOINT ["sh","start.sh"]
