version: "2.1"
services:
  webcenter-activemq:
    image: webcenter/activemq
    hostname: activemq
    expose: 
      - "8161"
    ports:
      - "8161:8161"
    volumes:
       - ~/Projects/sh-valley/docker-conf/webcenter-activemq/webcenter-activemq.xml:/opt/activemq/conf/activemq.xml
    #   - ~/Projects/sh-valley/docker-conf/elasticstack/es-kibana/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    networks:
      - default
# networks:
#   es-network:
